#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntua Bash script that uses# ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

ssh ubuntu@19.208.245.172 -i ~/.ssh/school
